compile:
	GOOS=freebsd GOARCH=386 go build -o bin/map-cli-freebsd-386 main.go
	GOOS=linux GOARCH=386 go build -o bin/map-cli-linux-386 main.go
	GOOS=windows GOARCH=386 go build -o bin/map-cli-windows-386.exe main.go